# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "WreelySocial.xcworkspace", scheme: "WreelySocial", include_bitcode: true)
    
    upload_to_testflight

	# upload to Testflight
	pilot(skip_waiting_for_build_processing: true)

	# slack(
	#   slack_url: "https://hooks.slack.com/services/IDS"
	# )

  	slack(message: "Successfully distributed a new beta build")
  end

  lane :release do
  build_app(scheme: "WreelySocial",
            workspace: "WreelySocial.xcworkspace",
            include_bitcode: true)

  upload_to_testflight

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
  end
end
